2019-05-13 10:44:45,861 - main.py[line:255] - DEBUG: loading data for train pnasnet5large_class6 ....
2019-05-13 10:47:17,142 - main.py[line:255] - DEBUG: loading data for train pnasnet5large_class6 ....
2019-05-13 10:47:20,405 - main.py[line:277] - DEBUG: start training cnn model.....
it will take several hours, or even dozens of....
2019-05-13 10:55:10,809 - main.py[line:213] - DEBUG: Epoch : 0  val_acc : 47.16267% ||| train_loss : 2.00744  val_loss : 1.84140  |||
2019-05-13 11:02:23,262 - main.py[line:213] - DEBUG: Epoch : 1  val_acc : 60.15132% ||| train_loss : 1.68641  val_loss : 1.38806  |||
2019-05-13 11:10:12,903 - main.py[line:213] - DEBUG: Epoch : 2  val_acc : 67.46532% ||| train_loss : 1.51619  val_loss : 1.08758  |||
2019-05-13 11:17:52,843 - main.py[line:213] - DEBUG: Epoch : 3  val_acc : 66.70870% ||| train_loss : 1.33736  val_loss : 1.00096  |||
2019-05-13 11:25:37,653 - main.py[line:213] - DEBUG: Epoch : 4  val_acc : 66.58260% ||| train_loss : 1.25888  val_loss : 1.04445  |||
2019-05-13 11:33:16,008 - main.py[line:213] - DEBUG: Epoch : 5  val_acc : 70.74401% ||| train_loss : 1.17212  val_loss : 0.89909  |||
2019-05-13 11:41:02,526 - main.py[line:213] - DEBUG: Epoch : 6  val_acc : 73.77049% ||| train_loss : 1.08106  val_loss : 0.84681  |||
2019-05-13 11:48:45,078 - main.py[line:213] - DEBUG: Epoch : 7  val_acc : 75.66204% ||| train_loss : 1.03683  val_loss : 0.74991  |||
2019-05-13 11:56:12,783 - main.py[line:213] - DEBUG: Epoch : 8  val_acc : 74.90542% ||| train_loss : 0.94198  val_loss : 0.75696  |||
2019-05-13 20:14:13,869 - main.py[line:265] - DEBUG: loading data for train pnasnet5large_class6 ....
2019-05-13 20:14:46,971 - main.py[line:265] - DEBUG: loading data for train pnasnet5large_class6 ....
2019-05-13 20:14:51,467 - main.py[line:287] - DEBUG: start training cnn model.....
it will take several hours, or even dozens of....
2019-05-13 20:14:51,474 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:436] - WARNING: Setting up a new session...
2019-05-13 20:14:51,507 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:489] - INFO: Socket refused connection, running socketless
2019-05-13 20:14:51,507 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:491] - ERROR: [Errno 111] Connection refused
2019-05-13 20:15:55,174 - main.py[line:265] - DEBUG: loading data for train pnasnet5large_class6 ....
2019-05-13 20:15:58,935 - main.py[line:287] - DEBUG: start training cnn model.....
it will take several hours, or even dozens of....
2019-05-13 20:15:58,939 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:436] - WARNING: Setting up a new session...
2019-05-13 20:15:58,954 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:470] - INFO: Visdom successfully connected to server
2019-05-13 20:18:24,035 - main.py[line:265] - DEBUG: loading data for train pnasnet5large_class6 ....
2019-05-13 20:18:27,446 - main.py[line:287] - DEBUG: start training cnn model.....
it will take several hours, or even dozens of....
2019-05-13 20:18:27,451 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:436] - WARNING: Setting up a new session...
2019-05-13 20:18:27,463 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:470] - INFO: Visdom successfully connected to server
2019-05-13 20:20:33,414 - main.py[line:265] - DEBUG: loading data for train pnasnet5large_class6 ....
2019-05-13 20:20:36,854 - main.py[line:287] - DEBUG: start training cnn model.....
it will take several hours, or even dozens of....
2019-05-13 20:20:36,858 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:436] - WARNING: Setting up a new session...
2019-05-13 20:20:36,870 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:470] - INFO: Visdom successfully connected to server
2019-05-13 20:23:36,997 - main.py[line:265] - DEBUG: loading data for train pnasnet5large_class6 ....
2019-05-13 20:23:41,028 - main.py[line:287] - DEBUG: start training cnn model.....
it will take several hours, or even dozens of....
2019-05-13 20:23:41,033 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:436] - WARNING: Setting up a new session...
2019-05-13 20:23:41,045 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:489] - INFO: Socket refused connection, running socketless
2019-05-13 20:23:41,045 - /home/wangzhaowei/anaconda3/envs/rongyf/lib/python3.6/site-packages/visdom/__init__.py[line:491] - ERROR: [Errno 111] Connection refused
2019-05-13 20:32:03,366 - main.py[line:223] - DEBUG: Epoch : 0  val_acc : 48.67591% ||| train_loss : 2.01376  val_loss : 1.85368  |||
2019-05-13 20:40:11,449 - main.py[line:223] - DEBUG: Epoch : 1  val_acc : 56.24212% ||| train_loss : 1.74073  val_loss : 1.45976  |||
2019-05-13 20:47:56,295 - main.py[line:223] - DEBUG: Epoch : 2  val_acc : 67.59142% ||| train_loss : 1.50765  val_loss : 1.10311  |||
2019-05-13 20:56:03,374 - main.py[line:223] - DEBUG: Epoch : 3  val_acc : 69.10467% ||| train_loss : 1.40247  val_loss : 0.97431  |||
2019-05-13 21:04:00,683 - main.py[line:223] - DEBUG: Epoch : 4  val_acc : 66.20429% ||| train_loss : 1.27150  val_loss : 0.98567  |||
2019-05-13 21:11:58,302 - main.py[line:223] - DEBUG: Epoch : 5  val_acc : 71.87894% ||| train_loss : 1.18492  val_loss : 0.86159  |||
2019-05-13 21:19:56,468 - main.py[line:223] - DEBUG: Epoch : 6  val_acc : 73.01387% ||| train_loss : 1.07623  val_loss : 0.78363  |||
2019-05-13 21:28:18,274 - main.py[line:223] - DEBUG: Epoch : 7  val_acc : 71.87894% ||| train_loss : 1.06042  val_loss : 0.79776  |||
2019-05-13 21:36:12,519 - main.py[line:223] - DEBUG: Epoch : 8  val_acc : 74.77932% ||| train_loss : 0.99321  val_loss : 0.72923  |||
2019-05-13 21:44:09,096 - main.py[line:223] - DEBUG: Epoch : 9  val_acc : 78.43632% ||| train_loss : 0.91203  val_loss : 0.64611  |||
2019-05-13 21:51:57,394 - main.py[line:223] - DEBUG: Epoch : 10  val_acc : 77.67970% ||| train_loss : 0.85556  val_loss : 0.63299  |||
2019-05-13 21:59:48,152 - main.py[line:223] - DEBUG: Epoch : 11  val_acc : 75.40984% ||| train_loss : 0.83549  val_loss : 0.73664  |||
2019-05-13 22:07:32,309 - main.py[line:223] - DEBUG: Epoch : 12  val_acc : 76.41866% ||| train_loss : 0.77904  val_loss : 0.69131  |||
2019-05-13 22:15:23,731 - main.py[line:223] - DEBUG: Epoch : 13  val_acc : 80.95839% ||| train_loss : 0.77179  val_loss : 0.55982  |||
2019-05-13 22:23:21,156 - main.py[line:223] - DEBUG: Epoch : 14  val_acc : 79.44515% ||| train_loss : 0.74901  val_loss : 0.58262  |||
2019-05-13 22:31:06,267 - main.py[line:223] - DEBUG: Epoch : 15  val_acc : 81.71501% ||| train_loss : 0.66604  val_loss : 0.50329  |||
2019-05-13 22:38:44,549 - main.py[line:223] - DEBUG: Epoch : 16  val_acc : 79.31904% ||| train_loss : 0.62936  val_loss : 0.55872  |||
2019-05-13 22:46:35,147 - main.py[line:223] - DEBUG: Epoch : 17  val_acc : 81.71501% ||| train_loss : 0.64548  val_loss : 0.51276  |||
2019-05-13 22:54:18,057 - main.py[line:223] - DEBUG: Epoch : 18  val_acc : 81.08449% ||| train_loss : 0.60200  val_loss : 0.56593  |||
2019-05-13 23:02:12,363 - main.py[line:223] - DEBUG: Epoch : 19  val_acc : 76.92308% ||| train_loss : 0.57855  val_loss : 0.65055  |||
2019-05-13 23:09:57,663 - main.py[line:223] - DEBUG: Epoch : 20  val_acc : 80.70618% ||| train_loss : 0.55505  val_loss : 0.58404  |||
2019-05-13 23:18:11,493 - main.py[line:223] - DEBUG: Epoch : 21  val_acc : 81.33670% ||| train_loss : 0.59755  val_loss : 0.56481  |||
2019-05-13 23:26:04,642 - main.py[line:223] - DEBUG: Epoch : 22  val_acc : 82.09332% ||| train_loss : 0.56756  val_loss : 0.53184  |||
2019-05-13 23:34:11,943 - main.py[line:223] - DEBUG: Epoch : 23  val_acc : 82.59773% ||| train_loss : 0.56144  val_loss : 0.50437  |||
2019-05-13 23:41:54,652 - main.py[line:223] - DEBUG: Epoch : 24  val_acc : 81.33670% ||| train_loss : 0.54571  val_loss : 0.56187  |||
2019-05-13 23:49:42,751 - main.py[line:223] - DEBUG: Epoch : 25  val_acc : 83.10214% ||| train_loss : 0.57020  val_loss : 0.55003  |||
2019-05-13 23:58:03,411 - main.py[line:223] - DEBUG: Epoch : 26  val_acc : 80.45397% ||| train_loss : 0.59818  val_loss : 0.57164  |||
